language: python

python:
    - 2.7

before_install:
  - pip2 install pysqlcipher --install-option="--bundled"

install:
  - pip2 install -r ../.travis/requirements.txt

script:
    - python pm.py < ../.travis/test.txt
